"""add_is_etf_to_stocks

Revision ID: 3c8c51065587
Revises: 643ee13400b4
Create Date: 2026-05-19 14:39:04.682594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8c51065587'
down_revision: Union[str, None] = '643ee13400b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('is_etf', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'is_etf')
    # ### end Alembic commands ###
