"""add_fundamental_metrics

Revision ID: 4dccb6b5cc5a
Revises: a31c2f3f7509
Create Date: 2026-05-19 12:23:01.264846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dccb6b5cc5a'
down_revision: Union[str, None] = 'a31c2f3f7509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_fundamentals', sa.Column('revenue_growth', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('stock_fundamentals', sa.Column('profit_margins', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('stock_fundamentals', sa.Column('debt_to_equity', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stock_fundamentals', sa.Column('return_on_equity', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('stock_fundamentals', sa.Column('free_cashflow', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('stock_fundamentals', sa.Column('beta', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('stock_fundamentals', sa.Column('forward_pe', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_fundamentals', 'forward_pe')
    op.drop_column('stock_fundamentals', 'beta')
    op.drop_column('stock_fundamentals', 'free_cashflow')
    op.drop_column('stock_fundamentals', 'return_on_equity')
    op.drop_column('stock_fundamentals', 'debt_to_equity')
    op.drop_column('stock_fundamentals', 'profit_margins')
    op.drop_column('stock_fundamentals', 'revenue_growth')
    # ### end Alembic commands ###
