"""add content visibility

Revision ID: 643ee13400b4
Revises: e3e26c64191f
Create Date: 2026-05-19 14:11:37.354101

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '643ee13400b4'
down_revision: Union[str, None] = 'e3e26c64191f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_visibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_key', sa.String(length=50), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_key', 'user_id', name='uq_content_visibility_key_user')
    )
    op.create_index(op.f('ix_content_visibility_id'), 'content_visibility', ['id'], unique=False)
    op.create_index('ix_content_visibility_scope', 'content_visibility', ['scope'], unique=False)
    op.create_index('ix_content_visibility_user_id', 'content_visibility', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_visibility_user_id', table_name='content_visibility')
    op.drop_index('ix_content_visibility_scope', table_name='content_visibility')
    op.drop_index(op.f('ix_content_visibility_id'), table_name='content_visibility')
    op.drop_table('content_visibility')
    # ### end Alembic commands ###
