"""add data_source to stock_sync_statuses

Revision ID: 7e0380611d66
Revises: ca0bd500790d
Create Date: 2026-05-19 09:31:11.693484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0380611d66'
down_revision: Union[str, None] = 'ca0bd500790d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_sync_statuses', sa.Column('data_source', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_sync_statuses', 'data_source')
    # ### end Alembic commands ###
