"""add_fundamentals_and_portfolio

Revision ID: a31c2f3f7509
Revises: 7e0380611d66
Create Date: 2026-05-19 10:56:31.580197

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a31c2f3f7509'
down_revision: Union[str, None] = '7e0380611d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_stock_id', 'portfolio_transactions', ['stock_id'], unique=False)
    op.create_index(op.f('ix_portfolio_transactions_id'), 'portfolio_transactions', ['id'], unique=False)
    op.create_index('ix_portfolio_user_id', 'portfolio_transactions', ['user_id'], unique=False)
    op.create_table('stock_fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('book_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('shares_outstanding', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('fifty_two_week_high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fifty_two_week_low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('long_business_summary', sa.String(length=2000), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id')
    )
    op.create_index(op.f('ix_stock_fundamentals_id'), 'stock_fundamentals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_fundamentals_id'), table_name='stock_fundamentals')
    op.drop_table('stock_fundamentals')
    op.drop_index('ix_portfolio_user_id', table_name='portfolio_transactions')
    op.drop_index(op.f('ix_portfolio_transactions_id'), table_name='portfolio_transactions')
    op.drop_index('ix_portfolio_stock_id', table_name='portfolio_transactions')
    op.drop_table('portfolio_transactions')
    # ### end Alembic commands ###
