"""add_target_prices_and_price_alerts

Revision ID: ca0bd500790d
Revises: 71418b14152e
Create Date: 2026-05-19 03:27:55.222854

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ca0bd500790d'
down_revision: Union[str, None] = '71418b14152e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_id'), 'price_alerts', ['id'], unique=False)
    op.create_index('ix_price_alerts_stock_id', 'price_alerts', ['stock_id'], unique=False)
    op.create_index('ix_price_alerts_user_id', 'price_alerts', ['user_id'], unique=False)
    op.create_table('stock_target_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('analyst', sa.String(length=100), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_target_prices_id'), 'stock_target_prices', ['id'], unique=False)
    op.create_index('ix_target_prices_stock_id', 'stock_target_prices', ['stock_id'], unique=False)
    op.create_index('ix_stock_prices_stock_id_date', 'stock_prices', ['stock_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_prices_stock_id_date', table_name='stock_prices')
    op.drop_index('ix_target_prices_stock_id', table_name='stock_target_prices')
    op.drop_index(op.f('ix_stock_target_prices_id'), table_name='stock_target_prices')
    op.drop_table('stock_target_prices')
    op.drop_index('ix_price_alerts_user_id', table_name='price_alerts')
    op.drop_index('ix_price_alerts_stock_id', table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_id'), table_name='price_alerts')
    op.drop_table('price_alerts')
    # ### end Alembic commands ###
